### createGuide
POST {{URL}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "firstName": "Thomas",
  "lastName": "Targaryen",
  "email": "Thomas.doe@example.com",
  "phone": "123-456-7890",
  "yearsOfExperience": 25
}

### getAllGuides
GET {{URL}}

### getGuideTripOverview
GET {{URL}}/overview

### deleteGuide
DELETE {{URL}}/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### getGuideOverviewTotalPrice
GET {{URL}}/totalprice