### createTrip
POST {{URL}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "startTime": "2024-07-10T15:00:00",
  "endTime": "2024-07-20T10:00:00",
  "startPosition": "Malta",
  "name": "Family Beach Vacation",
  "price": 5000.00,
  "category": "FAMILY"
}

### getTripById
GET {{URL}}/4

### getAllTrips
GET {{URL}}

### updateTrip
PUT {{URL}}/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "startTime": "2025-01-15T06:00:00",
  "endTime": "2025-01-25T18:00:00",
  "startPosition": "Himalayas",
  "name": "Adventure Mountain Trek",
  "price": 1500.00,
  "category": "ADVENTURE"
}

### deteleTrip
DELETE {{URL}}/4
Accept: application/json
Authorization: Bearer {{jwt_token}}

### addGuideToTrip
PUT {{URL}}/1/guides/2
Accept: application/json
Authorization: Bearer {{jwt_token}}

### getTripsByGuide
GET {{URL}}/guides/1/trips

### getTripsByCategory
GET {{URL}}/categories/ADVENTURE

### populateDatabase
POST {{URL}}/populate
Accept: application/json
Authorization: Bearer {{jwt_token}}

### getPackingItemsTotalWeight
GET {{URL}}/2/packing-items/total-weight

